import { readFileSync } from "node:fs";
import pg from "pg";
const env = Object.fromEntries(readFileSync(new URL("../.env.local", import.meta.url),"utf8").split(/\r?\n/).filter(l=>l.includes("=")&&!l.startsWith("#")).map(l=>{const i=l.indexOf("=");return [l.slice(0,i).trim(),l.slice(i+1).trim()];}));
const m=env.DATABASE_URL.match(/^postgres(?:ql)?:\/\/([^:]+):(.*)@([^:\/]+):(\d+)\/(.+)$/);
const c=new pg.Client({user:m[1],password:m[2],host:m[3],port:+m[4],database:m[5],ssl:{rejectUnauthorized:false}});
await c.connect();
const adm=(await c.query("select id from auth.users where email='demo.admin@gmail.com'")).rows[0].id;
const d=(await c.query("select d.id, d.pedido_id, p.estabelecimento_id, p.preco_total from disputas d join pedidos p on p.id=d.pedido_id where d.status='aberta' limit 1")).rows[0];
const reemb=Math.round((d.preco_total*0.5)*100)/100;
const antes=(await c.query("select saldo_carteira from estabelecimentos where id=$1",[d.estabelecimento_id])).rows[0].saldo_carteira;
await c.query("begin"); await c.query("set local role authenticated");
await c.query("select set_config('request.jwt.claims', json_build_object('sub',$1::text,'role','authenticated')::text, true)",[adm]);
const r=(await c.query("select resolver_disputa($1,$2,$3) ret",[d.id,"Reembolso parcial: avaria parcial confirmada.",reemb])).rows[0].ret;
const dep=(await c.query("select saldo_carteira from estabelecimentos where id=$1",[d.estabelecimento_id])).rows[0].saldo_carteira;
const dd=(await c.query("select status, valor_reembolso from disputas where id=$1",[d.id])).rows[0];
const tx=(await c.query("select tipo,valor from carteira_transacoes where pedido_id=$1 and tipo='reembolso'",[d.pedido_id])).rows[0];
await c.query("rollback");
console.log("frete do pedido:", d.preco_total, "| reembolso parcial pedido:", reemb);
console.log("RPC:", r, "| disputa:", dd.status, "valor_reembolso:", dd.valor_reembolso);
console.log("carteira lojista:", antes, "->", dep, "| transacao:", tx? tx.tipo+" R$"+tx.valor : "nenhuma");
await c.end();
